/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as GazetteRouteImport } from './routes/gazette'
import { Route as GmRouteImport } from './routes/gm'
import { Route as MapRouteImport } from './routes/map'
import { Route as MarketRouteImport } from './routes/market'
import { Route as GmFormulasRouteImport } from './routes/gm_.formulas'
import { Route as NationsIndexRouteImport } from './routes/nations.index'
import { Route as NationsAcronymRouteImport } from './routes/nations.$acronym'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteRoute = GazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const GmFormulasRoute = GmFormulasRouteImport.update({
  id: '/gm_/formulas',
  path: '/gm/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsIndexRoute = NationsIndexRouteImport.update({
  id: '/nations/',
  path: '/nations/',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsAcronymRoute = NationsAcronymRouteImport.update({
  id: '/nations/$acronym',
  path: '/nations/$acronym',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/exchange': typeof ExchangeRoute
  '/gazette': typeof GazetteRoute
  '/gm': typeof GmRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/gm/formulas': typeof GmFormulasRoute
  '/nations/$acronym': typeof NationsAcronymRoute
  '/nations/': typeof NationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/exchange': typeof ExchangeRoute
  '/gazette': typeof GazetteRoute
  '/gm': typeof GmRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/gm/formulas': typeof GmFormulasRoute
  '/nations/$acronym': typeof NationsAcronymRoute
  '/nations': typeof NationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/exchange': typeof ExchangeRoute
  '/gazette': typeof GazetteRoute
  '/gm': typeof GmRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/gm_/formulas': typeof GmFormulasRoute
  '/nations/$acronym': typeof NationsAcronymRoute
  '/nations/': typeof NationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/auth'
    | '/exchange'
    | '/gazette'
    | '/gm'
    | '/map'
    | '/market'
    | '/gm/formulas'
    | '/nations/$acronym'
    | '/nations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/auth'
    | '/exchange'
    | '/gazette'
    | '/gm'
    | '/map'
    | '/market'
    | '/gm/formulas'
    | '/nations/$acronym'
    | '/nations'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/auth'
    | '/exchange'
    | '/gazette'
    | '/gm'
    | '/map'
    | '/market'
    | '/gm_/formulas'
    | '/nations/$acronym'
    | '/nations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  ExchangeRoute: typeof ExchangeRoute
  GazetteRoute: typeof GazetteRoute
  GmRoute: typeof GmRoute
  MapRoute: typeof MapRoute
  MarketRoute: typeof MarketRoute
  GmFormulasRoute: typeof GmFormulasRoute
  NationsAcronymRoute: typeof NationsAcronymRoute
  NationsIndexRoute: typeof NationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazette': {
      id: '/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof GazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm_/formulas': {
      id: '/gm_/formulas'
      path: '/gm/formulas'
      fullPath: '/gm/formulas'
      preLoaderRoute: typeof GmFormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/': {
      id: '/nations/'
      path: '/nations'
      fullPath: '/nations/'
      preLoaderRoute: typeof NationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/$acronym': {
      id: '/nations/$acronym'
      path: '/nations/$acronym'
      fullPath: '/nations/$acronym'
      preLoaderRoute: typeof NationsAcronymRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  ExchangeRoute: ExchangeRoute,
  GazetteRoute: GazetteRoute,
  GmRoute: GmRoute,
  MapRoute: MapRoute,
  MarketRoute: MarketRoute,
  GmFormulasRoute: GmFormulasRoute,
  NationsAcronymRoute: NationsAcronymRoute,
  NationsIndexRoute: NationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
